name: Baseball - Blog
markdown: redcarpet
pygments: true
name: upteamisup
url: http://upteamisup.com
domain: upteamisup.com
author :
  name : upteamisup
  email : wjddkkl@koreatech.ac.kr
  github : https://github.com/upteamisup
  twitter : https://twitter.com/realronchi
  linkedin : http://br.linkedin.com/in/realronchi
